// <auto-generated />
using Lunatic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lunatic.Infrastructure.Migrations.LunaticML
{
    [DbContext(typeof(LunaticMLContext))]
    partial class LunaticMLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lunatic.Domain.MLModel.DaysToCompleteTaskEntry", b =>
                {
                    b.Property<int>("AssigneesCount")
                        .HasColumnType("int");

                    b.Property<double>("AverageCommentLength")
                        .HasColumnType("float");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<int>("DaysTookToComplete")
                        .HasColumnType("int");

                    b.Property<int>("DescriptionLength")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedDaysToComplete")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DaysToCompleteTaskEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
