// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
public partial class DaysToCompleteTaskPrediction
{
    /// <summary>
    /// model input class for DaysToCompleteTaskPrediction.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(1)]
        [ColumnName(@"AssigneesCount")]
        public float AssigneesCount { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"DescriptionLength")]
        public float DescriptionLength { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"CommentsCount")]
        public float CommentsCount { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"AverageCommentLength")]
        public float AverageCommentLength { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"Priority")]
        public float Priority { get; set; }

        [LoadColumn(6)]
        [ColumnName(@"DaysTookToComplete")]
        public float DaysTookToComplete { get; set; }

        [LoadColumn(7)]
        [ColumnName(@"ExpectedDaysToComplete")]
        public float ExpectedDaysToComplete { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for DaysToCompleteTaskPrediction.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"AssigneesCount")]
        public float AssigneesCount { get; set; }

        [ColumnName(@"DescriptionLength")]
        public float DescriptionLength { get; set; }

        [ColumnName(@"CommentsCount")]
        public float CommentsCount { get; set; }

        [ColumnName(@"AverageCommentLength")]
        public float AverageCommentLength { get; set; }

        [ColumnName(@"Priority")]
        public float Priority { get; set; }

        [ColumnName(@"DaysTookToComplete")]
        public uint DaysTookToComplete { get; set; }

        [ColumnName(@"ExpectedDaysToComplete")]
        public float ExpectedDaysToComplete { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"PredictedLabel")]
        public float PredictedLabel { get; set; }

        [ColumnName(@"Score")]
        public float[] Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("DaysToCompleteTaskPrediction.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict scores for all possible labels.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        var result = predEngine.Predict(input);
        return GetSortedScoresWithLabels(result);
    }

    /// <summary>
    /// Map the unlabeled result score array to the predicted label names.
    /// </summary>
    /// <param name="result">Prediction to get the labeled scores from.</param>
    /// <returns>Ordered list of label and score.</returns>
    /// <exception cref="Exception"></exception>
    public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
    {
        var unlabeledScores = result.Score;
        var labelNames = GetLabels(result);

        Dictionary<string, float> labledScores = new Dictionary<string, float>();
        for (int i = 0; i < labelNames.Count(); i++)
        {
            // Map the names to the predicted result score array
            var labelName = labelNames.ElementAt(i);
            labledScores.Add(labelName.ToString(), unlabeledScores[i]);
        }

        return labledScores.OrderByDescending(c => c.Value);
    }

    /// <summary>
    /// Get the ordered label names.
    /// </summary>
    /// <param name="result">Predicted result to get the labels from.</param>
    /// <returns>List of labels.</returns>
    /// <exception cref="Exception"></exception>
    private static IEnumerable<string> GetLabels(ModelOutput result)
    {
        var schema = PredictEngine.Value.OutputSchema;

        var labelColumn = schema.GetColumnOrNull("DaysTookToComplete");
        if (labelColumn == null)
        {
            throw new Exception("DaysTookToComplete column not found. Make sure the name searched for matches the name in the schema.");
        }

        // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
        var keyNames = new VBuffer<float>();
        labelColumn.Value.GetKeyValues(ref keyNames);
        return keyNames.DenseValues().Select(x => x.ToString());
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }
}
