// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<DaysToCompleteTaskPrediction.ModelInput, DaysToCompleteTaskPrediction.ModelOutput>()
	.FromFile("DaysToCompleteTaskPrediction.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c => {
	c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c => {
	c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});

// Define prediction route & handler
app.MapPost("/predict",
	async (PredictionEnginePool<DaysToCompleteTaskPrediction.ModelInput, DaysToCompleteTaskPrediction.ModelOutput>
			predictionEnginePool, DaysToCompleteTaskPrediction.ModelInput input) =>
				await Task.FromResult(predictionEnginePool.Predict(input).DaysTookToComplete));

// Run app
app.Run();
